// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: daemon.proto

package ipc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_daemon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{0}
}

type SetupJoystickRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserPermissions bool                   `protobuf:"varint,1,opt,name=userPermissions,proto3" json:"userPermissions,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SetupJoystickRequest) Reset() {
	*x = SetupJoystickRequest{}
	mi := &file_daemon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupJoystickRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupJoystickRequest) ProtoMessage() {}

func (x *SetupJoystickRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupJoystickRequest.ProtoReflect.Descriptor instead.
func (*SetupJoystickRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{1}
}

func (x *SetupJoystickRequest) GetUserPermissions() bool {
	if x != nil {
		return x.UserPermissions
	}
	return false
}

type SetupJoystickResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetupJoystickResponse) Reset() {
	*x = SetupJoystickResponse{}
	mi := &file_daemon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupJoystickResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupJoystickResponse) ProtoMessage() {}

func (x *SetupJoystickResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupJoystickResponse.ProtoReflect.Descriptor instead.
func (*SetupJoystickResponse) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{2}
}

func (x *SetupJoystickResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type SetupKeyboardRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserPermissions bool                   `protobuf:"varint,1,opt,name=userPermissions,proto3" json:"userPermissions,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SetupKeyboardRequest) Reset() {
	*x = SetupKeyboardRequest{}
	mi := &file_daemon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupKeyboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupKeyboardRequest) ProtoMessage() {}

func (x *SetupKeyboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupKeyboardRequest.ProtoReflect.Descriptor instead.
func (*SetupKeyboardRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{3}
}

func (x *SetupKeyboardRequest) GetUserPermissions() bool {
	if x != nil {
		return x.UserPermissions
	}
	return false
}

type SetupKeyboardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetupKeyboardResponse) Reset() {
	*x = SetupKeyboardResponse{}
	mi := &file_daemon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupKeyboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupKeyboardResponse) ProtoMessage() {}

func (x *SetupKeyboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupKeyboardResponse.ProtoReflect.Descriptor instead.
func (*SetupKeyboardResponse) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{4}
}

func (x *SetupKeyboardResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type SetupMouseRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserPermissions bool                   `protobuf:"varint,1,opt,name=userPermissions,proto3" json:"userPermissions,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SetupMouseRequest) Reset() {
	*x = SetupMouseRequest{}
	mi := &file_daemon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupMouseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupMouseRequest) ProtoMessage() {}

func (x *SetupMouseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupMouseRequest.ProtoReflect.Descriptor instead.
func (*SetupMouseRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{5}
}

func (x *SetupMouseRequest) GetUserPermissions() bool {
	if x != nil {
		return x.UserPermissions
	}
	return false
}

type SetupMouseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetupMouseResponse) Reset() {
	*x = SetupMouseResponse{}
	mi := &file_daemon_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupMouseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupMouseResponse) ProtoMessage() {}

func (x *SetupMouseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupMouseResponse.ProtoReflect.Descriptor instead.
func (*SetupMouseResponse) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{6}
}

func (x *SetupMouseResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type WriteBluetoothHIDDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteBluetoothHIDDataRequest) Reset() {
	*x = WriteBluetoothHIDDataRequest{}
	mi := &file_daemon_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteBluetoothHIDDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteBluetoothHIDDataRequest) ProtoMessage() {}

func (x *WriteBluetoothHIDDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteBluetoothHIDDataRequest.ProtoReflect.Descriptor instead.
func (*WriteBluetoothHIDDataRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{7}
}

func (x *WriteBluetoothHIDDataRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_daemon_proto protoreflect.FileDescriptor

const file_daemon_proto_rawDesc = "" +
	"\n" +
	"\fdaemon.proto\x12\adeckjoy\"\a\n" +
	"\x05Empty\"@\n" +
	"\x14SetupJoystickRequest\x12(\n" +
	"\x0fuserPermissions\x18\x01 \x01(\bR\x0fuserPermissions\"+\n" +
	"\x15SetupJoystickResponse\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"@\n" +
	"\x14SetupKeyboardRequest\x12(\n" +
	"\x0fuserPermissions\x18\x01 \x01(\bR\x0fuserPermissions\"+\n" +
	"\x15SetupKeyboardResponse\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"=\n" +
	"\x11SetupMouseRequest\x12(\n" +
	"\x0fuserPermissions\x18\x01 \x01(\bR\x0fuserPermissions\"(\n" +
	"\x12SetupMouseResponse\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"2\n" +
	"\x1cWriteBluetoothHIDDataRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data2\x95\x04\n" +
	"\rDeckJoyDaemon\x12(\n" +
	"\x04Stop\x12\x0e.deckjoy.Empty\x1a\x0e.deckjoy.Empty\"\x00\x12+\n" +
	"\aInitUSB\x12\x0e.deckjoy.Empty\x1a\x0e.deckjoy.Empty\"\x00\x12S\n" +
	"\x10SetupUSBJoystick\x12\x1d.deckjoy.SetupJoystickRequest\x1a\x1e.deckjoy.SetupJoystickResponse\"\x00\x12S\n" +
	"\x10SetupUSBKeyboard\x12\x1d.deckjoy.SetupKeyboardRequest\x1a\x1e.deckjoy.SetupKeyboardResponse\"\x00\x12J\n" +
	"\rSetupUSBMouse\x12\x1a.deckjoy.SetupMouseRequest\x1a\x1b.deckjoy.SetupMouseResponse\"\x00\x122\n" +
	"\x0eInstallSudoers\x12\x0e.deckjoy.Empty\x1a\x0e.deckjoy.Empty\"\x00\x121\n" +
	"\rInitBluetooth\x12\x0e.deckjoy.Empty\x1a\x0e.deckjoy.Empty\"\x00\x12P\n" +
	"\x15WriteBluetoothHIDData\x12%.deckjoy.WriteBluetoothHIDDataRequest\x1a\x0e.deckjoy.Empty\"\x00B$Z\"github.com/lucaber/deckjoy/pkg/ipcb\x06proto3"

var (
	file_daemon_proto_rawDescOnce sync.Once
	file_daemon_proto_rawDescData []byte
)

func file_daemon_proto_rawDescGZIP() []byte {
	file_daemon_proto_rawDescOnce.Do(func() {
		file_daemon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_daemon_proto_rawDesc), len(file_daemon_proto_rawDesc)))
	})
	return file_daemon_proto_rawDescData
}

var file_daemon_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_daemon_proto_goTypes = []any{
	(*Empty)(nil),                        // 0: deckjoy.Empty
	(*SetupJoystickRequest)(nil),         // 1: deckjoy.SetupJoystickRequest
	(*SetupJoystickResponse)(nil),        // 2: deckjoy.SetupJoystickResponse
	(*SetupKeyboardRequest)(nil),         // 3: deckjoy.SetupKeyboardRequest
	(*SetupKeyboardResponse)(nil),        // 4: deckjoy.SetupKeyboardResponse
	(*SetupMouseRequest)(nil),            // 5: deckjoy.SetupMouseRequest
	(*SetupMouseResponse)(nil),           // 6: deckjoy.SetupMouseResponse
	(*WriteBluetoothHIDDataRequest)(nil), // 7: deckjoy.WriteBluetoothHIDDataRequest
}
var file_daemon_proto_depIdxs = []int32{
	0, // 0: deckjoy.DeckJoyDaemon.Stop:input_type -> deckjoy.Empty
	0, // 1: deckjoy.DeckJoyDaemon.InitUSB:input_type -> deckjoy.Empty
	1, // 2: deckjoy.DeckJoyDaemon.SetupUSBJoystick:input_type -> deckjoy.SetupJoystickRequest
	3, // 3: deckjoy.DeckJoyDaemon.SetupUSBKeyboard:input_type -> deckjoy.SetupKeyboardRequest
	5, // 4: deckjoy.DeckJoyDaemon.SetupUSBMouse:input_type -> deckjoy.SetupMouseRequest
	0, // 5: deckjoy.DeckJoyDaemon.InstallSudoers:input_type -> deckjoy.Empty
	0, // 6: deckjoy.DeckJoyDaemon.InitBluetooth:input_type -> deckjoy.Empty
	7, // 7: deckjoy.DeckJoyDaemon.WriteBluetoothHIDData:input_type -> deckjoy.WriteBluetoothHIDDataRequest
	0, // 8: deckjoy.DeckJoyDaemon.Stop:output_type -> deckjoy.Empty
	0, // 9: deckjoy.DeckJoyDaemon.InitUSB:output_type -> deckjoy.Empty
	2, // 10: deckjoy.DeckJoyDaemon.SetupUSBJoystick:output_type -> deckjoy.SetupJoystickResponse
	4, // 11: deckjoy.DeckJoyDaemon.SetupUSBKeyboard:output_type -> deckjoy.SetupKeyboardResponse
	6, // 12: deckjoy.DeckJoyDaemon.SetupUSBMouse:output_type -> deckjoy.SetupMouseResponse
	0, // 13: deckjoy.DeckJoyDaemon.InstallSudoers:output_type -> deckjoy.Empty
	0, // 14: deckjoy.DeckJoyDaemon.InitBluetooth:output_type -> deckjoy.Empty
	0, // 15: deckjoy.DeckJoyDaemon.WriteBluetoothHIDData:output_type -> deckjoy.Empty
	8, // [8:16] is the sub-list for method output_type
	0, // [0:8] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_daemon_proto_init() }
func file_daemon_proto_init() {
	if File_daemon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_daemon_proto_rawDesc), len(file_daemon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_daemon_proto_goTypes,
		DependencyIndexes: file_daemon_proto_depIdxs,
		MessageInfos:      file_daemon_proto_msgTypes,
	}.Build()
	File_daemon_proto = out.File
	file_daemon_proto_goTypes = nil
	file_daemon_proto_depIdxs = nil
}
