// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: daemon.proto

package ipc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DeckJoyDaemon_Stop_FullMethodName                  = "/deckjoy.DeckJoyDaemon/Stop"
	DeckJoyDaemon_InitUSB_FullMethodName               = "/deckjoy.DeckJoyDaemon/InitUSB"
	DeckJoyDaemon_SetupUSBJoystick_FullMethodName      = "/deckjoy.DeckJoyDaemon/SetupUSBJoystick"
	DeckJoyDaemon_SetupUSBKeyboard_FullMethodName      = "/deckjoy.DeckJoyDaemon/SetupUSBKeyboard"
	DeckJoyDaemon_SetupUSBMouse_FullMethodName         = "/deckjoy.DeckJoyDaemon/SetupUSBMouse"
	DeckJoyDaemon_InstallSudoers_FullMethodName        = "/deckjoy.DeckJoyDaemon/InstallSudoers"
	DeckJoyDaemon_InitBluetooth_FullMethodName         = "/deckjoy.DeckJoyDaemon/InitBluetooth"
	DeckJoyDaemon_WriteBluetoothHIDData_FullMethodName = "/deckjoy.DeckJoyDaemon/WriteBluetoothHIDData"
)

// DeckJoyDaemonClient is the client API for DeckJoyDaemon service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeckJoyDaemonClient interface {
	Stop(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	InitUSB(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	SetupUSBJoystick(ctx context.Context, in *SetupJoystickRequest, opts ...grpc.CallOption) (*SetupJoystickResponse, error)
	SetupUSBKeyboard(ctx context.Context, in *SetupKeyboardRequest, opts ...grpc.CallOption) (*SetupKeyboardResponse, error)
	SetupUSBMouse(ctx context.Context, in *SetupMouseRequest, opts ...grpc.CallOption) (*SetupMouseResponse, error)
	InstallSudoers(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	InitBluetooth(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	WriteBluetoothHIDData(ctx context.Context, in *WriteBluetoothHIDDataRequest, opts ...grpc.CallOption) (*Empty, error)
}

type deckJoyDaemonClient struct {
	cc grpc.ClientConnInterface
}

func NewDeckJoyDaemonClient(cc grpc.ClientConnInterface) DeckJoyDaemonClient {
	return &deckJoyDaemonClient{cc}
}

func (c *deckJoyDaemonClient) Stop(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, DeckJoyDaemon_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deckJoyDaemonClient) InitUSB(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, DeckJoyDaemon_InitUSB_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deckJoyDaemonClient) SetupUSBJoystick(ctx context.Context, in *SetupJoystickRequest, opts ...grpc.CallOption) (*SetupJoystickResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetupJoystickResponse)
	err := c.cc.Invoke(ctx, DeckJoyDaemon_SetupUSBJoystick_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deckJoyDaemonClient) SetupUSBKeyboard(ctx context.Context, in *SetupKeyboardRequest, opts ...grpc.CallOption) (*SetupKeyboardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetupKeyboardResponse)
	err := c.cc.Invoke(ctx, DeckJoyDaemon_SetupUSBKeyboard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deckJoyDaemonClient) SetupUSBMouse(ctx context.Context, in *SetupMouseRequest, opts ...grpc.CallOption) (*SetupMouseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetupMouseResponse)
	err := c.cc.Invoke(ctx, DeckJoyDaemon_SetupUSBMouse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deckJoyDaemonClient) InstallSudoers(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, DeckJoyDaemon_InstallSudoers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deckJoyDaemonClient) InitBluetooth(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, DeckJoyDaemon_InitBluetooth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deckJoyDaemonClient) WriteBluetoothHIDData(ctx context.Context, in *WriteBluetoothHIDDataRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, DeckJoyDaemon_WriteBluetoothHIDData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeckJoyDaemonServer is the server API for DeckJoyDaemon service.
// All implementations must embed UnimplementedDeckJoyDaemonServer
// for forward compatibility.
type DeckJoyDaemonServer interface {
	Stop(context.Context, *Empty) (*Empty, error)
	InitUSB(context.Context, *Empty) (*Empty, error)
	SetupUSBJoystick(context.Context, *SetupJoystickRequest) (*SetupJoystickResponse, error)
	SetupUSBKeyboard(context.Context, *SetupKeyboardRequest) (*SetupKeyboardResponse, error)
	SetupUSBMouse(context.Context, *SetupMouseRequest) (*SetupMouseResponse, error)
	InstallSudoers(context.Context, *Empty) (*Empty, error)
	InitBluetooth(context.Context, *Empty) (*Empty, error)
	WriteBluetoothHIDData(context.Context, *WriteBluetoothHIDDataRequest) (*Empty, error)
	mustEmbedUnimplementedDeckJoyDaemonServer()
}

// UnimplementedDeckJoyDaemonServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeckJoyDaemonServer struct{}

func (UnimplementedDeckJoyDaemonServer) Stop(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedDeckJoyDaemonServer) InitUSB(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitUSB not implemented")
}
func (UnimplementedDeckJoyDaemonServer) SetupUSBJoystick(context.Context, *SetupJoystickRequest) (*SetupJoystickResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetupUSBJoystick not implemented")
}
func (UnimplementedDeckJoyDaemonServer) SetupUSBKeyboard(context.Context, *SetupKeyboardRequest) (*SetupKeyboardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetupUSBKeyboard not implemented")
}
func (UnimplementedDeckJoyDaemonServer) SetupUSBMouse(context.Context, *SetupMouseRequest) (*SetupMouseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetupUSBMouse not implemented")
}
func (UnimplementedDeckJoyDaemonServer) InstallSudoers(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InstallSudoers not implemented")
}
func (UnimplementedDeckJoyDaemonServer) InitBluetooth(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitBluetooth not implemented")
}
func (UnimplementedDeckJoyDaemonServer) WriteBluetoothHIDData(context.Context, *WriteBluetoothHIDDataRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WriteBluetoothHIDData not implemented")
}
func (UnimplementedDeckJoyDaemonServer) mustEmbedUnimplementedDeckJoyDaemonServer() {}
func (UnimplementedDeckJoyDaemonServer) testEmbeddedByValue()                       {}

// UnsafeDeckJoyDaemonServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeckJoyDaemonServer will
// result in compilation errors.
type UnsafeDeckJoyDaemonServer interface {
	mustEmbedUnimplementedDeckJoyDaemonServer()
}

func RegisterDeckJoyDaemonServer(s grpc.ServiceRegistrar, srv DeckJoyDaemonServer) {
	// If the following call pancis, it indicates UnimplementedDeckJoyDaemonServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeckJoyDaemon_ServiceDesc, srv)
}

func _DeckJoyDaemon_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeckJoyDaemonServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeckJoyDaemon_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeckJoyDaemonServer).Stop(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeckJoyDaemon_InitUSB_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeckJoyDaemonServer).InitUSB(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeckJoyDaemon_InitUSB_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeckJoyDaemonServer).InitUSB(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeckJoyDaemon_SetupUSBJoystick_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetupJoystickRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeckJoyDaemonServer).SetupUSBJoystick(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeckJoyDaemon_SetupUSBJoystick_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeckJoyDaemonServer).SetupUSBJoystick(ctx, req.(*SetupJoystickRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeckJoyDaemon_SetupUSBKeyboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetupKeyboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeckJoyDaemonServer).SetupUSBKeyboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeckJoyDaemon_SetupUSBKeyboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeckJoyDaemonServer).SetupUSBKeyboard(ctx, req.(*SetupKeyboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeckJoyDaemon_SetupUSBMouse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetupMouseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeckJoyDaemonServer).SetupUSBMouse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeckJoyDaemon_SetupUSBMouse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeckJoyDaemonServer).SetupUSBMouse(ctx, req.(*SetupMouseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeckJoyDaemon_InstallSudoers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeckJoyDaemonServer).InstallSudoers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeckJoyDaemon_InstallSudoers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeckJoyDaemonServer).InstallSudoers(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeckJoyDaemon_InitBluetooth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeckJoyDaemonServer).InitBluetooth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeckJoyDaemon_InitBluetooth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeckJoyDaemonServer).InitBluetooth(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeckJoyDaemon_WriteBluetoothHIDData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteBluetoothHIDDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeckJoyDaemonServer).WriteBluetoothHIDData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeckJoyDaemon_WriteBluetoothHIDData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeckJoyDaemonServer).WriteBluetoothHIDData(ctx, req.(*WriteBluetoothHIDDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeckJoyDaemon_ServiceDesc is the grpc.ServiceDesc for DeckJoyDaemon service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeckJoyDaemon_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "deckjoy.DeckJoyDaemon",
	HandlerType: (*DeckJoyDaemonServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Stop",
			Handler:    _DeckJoyDaemon_Stop_Handler,
		},
		{
			MethodName: "InitUSB",
			Handler:    _DeckJoyDaemon_InitUSB_Handler,
		},
		{
			MethodName: "SetupUSBJoystick",
			Handler:    _DeckJoyDaemon_SetupUSBJoystick_Handler,
		},
		{
			MethodName: "SetupUSBKeyboard",
			Handler:    _DeckJoyDaemon_SetupUSBKeyboard_Handler,
		},
		{
			MethodName: "SetupUSBMouse",
			Handler:    _DeckJoyDaemon_SetupUSBMouse_Handler,
		},
		{
			MethodName: "InstallSudoers",
			Handler:    _DeckJoyDaemon_InstallSudoers_Handler,
		},
		{
			MethodName: "InitBluetooth",
			Handler:    _DeckJoyDaemon_InitBluetooth_Handler,
		},
		{
			MethodName: "WriteBluetoothHIDData",
			Handler:    _DeckJoyDaemon_WriteBluetoothHIDData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "daemon.proto",
}
