syntax = "proto3";
option go_package = "github.com/lucaber/deckjoy/pkg/ipc";

package deckjoy;

service DeckJoyDaemon {
  rpc Stop (Empty) returns (Empty) {}
  rpc InitUSB (Empty) returns (Empty) {}
  rpc SetupUSBJoystick (SetupJoystickRequest) returns (SetupJoystickResponse) {}
  rpc SetupUSBKeyboard (SetupKeyboardRequest) returns (SetupKeyboardResponse) {}
  rpc SetupUSBMouse (SetupMouseRequest) returns (SetupMouseResponse) {}
  rpc InstallSudoers(Empty) returns (Empty) {}
  rpc InitBluetooth (Empty) returns (Empty) {}
  rpc WriteBluetoothHIDData (WriteBluetoothHIDDataRequest) returns (Empty) {}
}

message Empty {
}

message SetupJoystickRequest {
  bool userPermissions = 1;
}

message SetupJoystickResponse {
  string path = 1;
}

message SetupKeyboardRequest {
  bool userPermissions = 1;
}

message SetupKeyboardResponse {
  string path = 1;
}

message SetupMouseRequest {
  bool userPermissions = 1;
}

message SetupMouseResponse {
  string path = 1;
}

message WriteBluetoothHIDDataRequest {
  bytes data = 1;
}
