package hid

// https://gist.github.com/MightyPork/6da26e382a7ad91b5496ee55fdc73db2

type KeyboardModKey byte

const (
	KeyboardModKeyLCtrl  = KeyboardModKey(0x01)
	KeyboardModKeyLShift = KeyboardModKey(0x02)
	KeyboardModKeyLAlt   = KeyboardModKey(0x04)
	KeyboardModKeyLMeta  = KeyboardModKey(0x08)
	KeyboardModKeyRCtrl  = KeyboardModKey(0x10)
	KeyboardModKeyRShift = KeyboardModKey(0x20)
	KeyboardModKeyRAlt   = KeyboardModKey(0x40)
	KeyboardModKeyRMeta  = KeyboardModKey(0x80)
)

type KeyboardKey byte

const (
	KeyErr = KeyboardKey(0x01)

	KeyboardKeyA = KeyboardKey(0x04)
	KeyboardKeyB = KeyboardKey(0x05)
	KeyboardKeyC = KeyboardKey(0x06)
	KeyboardKeyD = KeyboardKey(0x07)
	KeyboardKeyE = KeyboardKey(0x08)
	KeyboardKeyF = KeyboardKey(0x09)
	KeyboardKeyG = KeyboardKey(0x0a)
	KeyboardKeyH = KeyboardKey(0x0b)
	KeyboardKeyI = KeyboardKey(0x0c)
	KeyboardKeyJ = KeyboardKey(0x0d)
	KeyboardKeyK = KeyboardKey(0x0e)
	KeyboardKeyL = KeyboardKey(0x0f)
	KeyboardKeyM = KeyboardKey(0x10)
	KeyboardKeyN = KeyboardKey(0x11)
	KeyboardKeyO = KeyboardKey(0x12)
	KeyboardKeyP = KeyboardKey(0x13)
	KeyboardKeyQ = KeyboardKey(0x14)
	KeyboardKeyR = KeyboardKey(0x15)
	KeyboardKeyS = KeyboardKey(0x16)
	KeyboardKeyT = KeyboardKey(0x17)
	KeyboardKeyU = KeyboardKey(0x18)
	KeyboardKeyV = KeyboardKey(0x19)
	KeyboardKeyW = KeyboardKey(0x1a)
	KeyboardKeyX = KeyboardKey(0x1b)
	KeyboardKeyY = KeyboardKey(0x1c)
	KeyboardKeyZ = KeyboardKey(0x1d)

	KeyboardKey1 = KeyboardKey(0x1e)
	KeyboardKey2 = KeyboardKey(0x1f)
	KeyboardKey3 = KeyboardKey(0x20)
	KeyboardKey4 = KeyboardKey(0x21)
	KeyboardKey5 = KeyboardKey(0x22)
	KeyboardKey6 = KeyboardKey(0x23)
	KeyboardKey7 = KeyboardKey(0x24)
	KeyboardKey8 = KeyboardKey(0x25)
	KeyboardKey9 = KeyboardKey(0x26)
	KeyboardKey0 = KeyboardKey(0x27)

	KeyboardKeyENTER      = KeyboardKey(0x28)
	KeyboardKeyESC        = KeyboardKey(0x29)
	KeyboardKeyBACKSPACE  = KeyboardKey(0x2a)
	KeyboardKeyTAB        = KeyboardKey(0x2b)
	KeyboardKeySPACE      = KeyboardKey(0x2c)
	KeyboardKeyMINUS      = KeyboardKey(0x2d)
	KeyboardKeyEQUAL      = KeyboardKey(0x2e)
	KeyboardKeyLEFTBRACE  = KeyboardKey(0x2f)
	KeyboardKeyRIGHTBRACE = KeyboardKey(0x30)
	KeyboardKeyBACKSLASH  = KeyboardKey(0x31)
	KeyboardKeyHASHTILDE  = KeyboardKey(0x32)
	KeyboardKeySEMICOLON  = KeyboardKey(0x33)
	KeyboardKeyAPOSTROPHE = KeyboardKey(0x34)
	KeyboardKeyGRAVE      = KeyboardKey(0x35)
	KeyboardKeyCOMMA      = KeyboardKey(0x36)
	KeyboardKeyDOT        = KeyboardKey(0x37)
	KeyboardKeySLASH      = KeyboardKey(0x38)
	KeyboardKeyCAPSLOCK   = KeyboardKey(0x39)

	KeyboardKeyF1  = KeyboardKey(0x3a)
	KeyboardKeyF2  = KeyboardKey(0x3b)
	KeyboardKeyF3  = KeyboardKey(0x3c)
	KeyboardKeyF4  = KeyboardKey(0x3d)
	KeyboardKeyF5  = KeyboardKey(0x3e)
	KeyboardKeyF6  = KeyboardKey(0x3f)
	KeyboardKeyF7  = KeyboardKey(0x40)
	KeyboardKeyF8  = KeyboardKey(0x41)
	KeyboardKeyF9  = KeyboardKey(0x42)
	KeyboardKeyF10 = KeyboardKey(0x43)
	KeyboardKeyF11 = KeyboardKey(0x44)
	KeyboardKeyF12 = KeyboardKey(0x45)

	KeyboardKeySYSRQ      = KeyboardKey(0x46)
	KeyboardKeySCROLLLOCK = KeyboardKey(0x47)
	KeyboardKeyPAUSE      = KeyboardKey(0x48)
	KeyboardKeyINSERT     = KeyboardKey(0x49)
	KeyboardKeyHOME       = KeyboardKey(0x4a)
	KeyboardKeyPAGEUP     = KeyboardKey(0x4b)
	KeyboardKeyDELETE     = KeyboardKey(0x4c)
	KeyboardKeyEND        = KeyboardKey(0x4d)
	KeyboardKeyPAGEDOWN   = KeyboardKey(0x4e)
	KeyboardKeyRIGHT      = KeyboardKey(0x4f)
	KeyboardKeyLEFT       = KeyboardKey(0x50)
	KeyboardKeyDOWN       = KeyboardKey(0x51)
	KeyboardKeyUP         = KeyboardKey(0x52)

	KeyboardKeyNUMLOCK    = KeyboardKey(0x53)
	KeyboardKeyKPSLASH    = KeyboardKey(0x54)
	KeyboardKeyKPASTERISK = KeyboardKey(0x55)
	KeyboardKeyKPMINUS    = KeyboardKey(0x56)
	KeyboardKeyKPPLUS     = KeyboardKey(0x57)
	KeyboardKeyKPENTER    = KeyboardKey(0x58)
	KeyboardKeyKP1        = KeyboardKey(0x59)
	KeyboardKeyKP2        = KeyboardKey(0x5a)
	KeyboardKeyKP3        = KeyboardKey(0x5b)
	KeyboardKeyKP4        = KeyboardKey(0x5c)
	KeyboardKeyKP5        = KeyboardKey(0x5d)
	KeyboardKeyKP6        = KeyboardKey(0x5e)
	KeyboardKeyKP7        = KeyboardKey(0x5f)
	KeyboardKeyKP8        = KeyboardKey(0x60)
	KeyboardKeyKP9        = KeyboardKey(0x61)
	KeyboardKeyKP0        = KeyboardKey(0x62)
	KeyboardKeyKPDOT      = KeyboardKey(0x63)

	KeyboardKey102ND   = KeyboardKey(0x64)
	KeyboardKeyCOMPOSE = KeyboardKey(0x65)
	KeyboardKeyPOWER   = KeyboardKey(0x66)
	KeyboardKeyKPEQUAL = KeyboardKey(0x67)
)
